version: '2'
services:

  app:
    build: ./app/
    container_name: cerbero_app
    volumes:
      - ./code:/var/www/html
    ports: 
      - "8080:80"
      - "443:443"
    links: 
      - db

  db:
    build: ./db/
    container_name: cerbero_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: producao
      MYSQL_PASSWORD: sentinela10bda
      MYSQL_DATABASE: cerbero
      MYSQL_ROOT_PASSWORD: '$$3nt1n3l4'
  pma:
    container_name: cerbero_pma
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports: 
    - "8081:80"
